version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/php-server/laravel-graphql"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"