#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#npm run test
npx tsc --noEmit
npx lint-staged
npx prisma format
npm run lint # Note: "npx eslint" seems to do the same thing, but it also suggests you to run --fix. It seems better...

#npx prettier "**/*.{tsx,ts,css}" "tailwind.config.js"
